name: Deploy
run-name: Deploy

on:
  workflow_call:
    inputs:
      target_env:
        description: 'The deployment environment e.g. production or development'
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_env }}

    steps:
      - name: Checkout code
        # Checks out the repository code.
        uses: actions/checkout@v4

      - name: Set up SSH key
        # Sets up the SSH key for the server.
        run: |
          # Create the .ssh directory if it doesn't exist.
          mkdir -p ~/.ssh
          # Write the SSH private key to file.
          echo "${{ secrets.DEPLOYMENT_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Add the server to known_hosts to avoid authenticity prompts.
          ssh-keyscan -H ${{ secrets.DEPLOYMENT_SERVER }} >> ~/.ssh/known_hosts

      - name: Download build artifacts
        # Downloads dist folder
        uses: actions/download-artifact@v4
        with:
          name: ${{ vars.PROJECT_NAME }}
          path: ${{ vars.PROJECT_NAME }}

      # temp: for debugging
      - name: List files after artifact download
        run: |
          echo ">>> Listing the top-level workspace directories:"
          ls -la
          echo ">>> Listing contents of ${{ vars.PROJECT_NAME }} (artifact folder):"
          ls -la ${{ vars.PROJECT_NAME }}
          echo ">>> Full recursive tree of ${{ vars.PROJECT_NAME }}:"
          ls -R ${{ vars.PROJECT_NAME }}

      - name: Deploy files to VPS
        # Clears existing files and deploy new files
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOYMENT_SSH_USER }}@${{ secrets.DEPLOYMENT_SERVER }} \
            "mkdir -p /var/www/rcb/${{ vars.PROJECT_NAME }} && rm -rf /var/www/rcb/${{ vars.PROJECT_NAME }}/*"

          scp -o StrictHostKeyChecking=no -r ${{ vars.PROJECT_NAME }}/*  \
            ${{ secrets.DEPLOYMENT_SSH_USER }}@${{ secrets.DEPLOYMENT_SERVER }}:/var/www/rcb/${{ vars.PROJECT_NAME }}/
