name: Lint, Build & Test
run-name: Lint, Build & Test

permissions:
  contents: read
  actions: read

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use"
        required: true
        type: string
      target_env:
        description: 'The deployment environment e.g. production or development'
        required: true
        type: string
      skip_deploy:
        description: 'Skip the deploy step (true/false)'
        required: true
        type: boolean

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_env }}

    steps:
      - name: Checkout code
        # Checks out the repository code.
        uses: actions/checkout@v4

      - name: Setup Node.js (Latest)
        # Sets up NodeJS environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install Dependencies
        # Installs dependencies
        run: npm ci

      - name: Run Linter
        # Runs lint checks
        run: npm run lint

  test:
    needs: lint
    name: Run Tests
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_env }}

    steps:
      - name: Checkout code
        # Checks out the repository code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ inputs.node-version }}
        # Sets up NodeJS environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install Dependencies
        # Installs dependencies
        run: npm ci

      - name: Run Tests
        # Runs test cases
        run: npm run test

  build:
    needs: test
    name: Run Build Process
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_env }}

    steps:
      - name: Checkout code
        # Checks out the repository code.
        uses: actions/checkout@v4

      - name: Load env file
        # Loads environment variables from file
        run: echo "${{ secrets.APPLICATION_ENV_FILE }}" > .env
      
      - name: Setup Node.js ${{ inputs.node-version }}
        # Sets up NodeJS environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install Dependencies
        # Install dependencies
        run: npm ci

      - name: Build Project
        # Builds project
        run: npm run build --if-present

      - name: Upload build artifact (dist)
        # Uploads build output
        uses: actions/upload-artifact@v4
        with:
          name: ${{ vars.PROJECT_NAME }}-${{ inputs.target_env }}
          path: dist
          retention-days: 1 

  trigger-deploy:
    needs: build
    name: Deploy
    if: ${{ inputs.skip_deploy == false }}
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}